version: '2.0.0.{build}'

environment:
  matrix:
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

    - PYTHON: C:\Python38-x64
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 64

    - PYTHON: C:\Python39-x64
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 64
    
    - PYTHON: C:\Python310-x64
      PYTHON_VERSION: 3.10
      PYTHON_ARCH: 64

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  - '%PYTHON%\python.exe --version'
  - '%PYTHON%\python.exe -m pip install pipenv'
  - '%PYTHON%\python.exe -m pipenv install --dev'

build: off

test_script:
  - '%PYTHON%\python.exe -m pipenv run py.test --cov=persiantools tests/ -v'
