version: '2.0.0.{build}'

environment:
  matrix:
    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

    - PYTHON: C:\Python37
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32

    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

    - PYTHON: C:\Python38
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 32

    - PYTHON: C:\Python38-x64
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 64

    - PYTHON: C:\Python39
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 32

    - PYTHON: C:\Python39-x64
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 64

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  - python --version
  - python -c "import sys, platform, struct;
    print(sys.platform, platform.machine(), struct.calcsize('P')*8)"

  - python -m pip install -U pip setuptools wheel
  - pip install pipenv
  - pipenv install --dev

build: off

test_script:
  - pipenv run py.test --cov=persiantools tests/ -v
