repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [ '--fix=lf' ]

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        types_or: [ python, pyi ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort

