os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "pypy3"

install:
  - python -c "import sys, platform, struct;
    print(sys.platform, platform.machine(), struct.calcsize('P')*8)"
  - python -m pip install pipenv
  - python -m pip install coveralls
  - pipenv install --dev

script:
  py.test --cov=persiantools tests/ -v

after_success:
  coveralls
