name: ci

on: [push]

jobs:
  tests:
    name: ${{matrix.os}} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', pypy-3.8]
        include:
          - python-version: '3.6'
            os: ubuntu-latest
          - python-version: pypy-3.9
            os: ubuntu-latest
          - python-version: pypy-3.9
            os: windows-latest
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python --version

      - name: Get python path
        id: python-path
        run: |
          echo ::set-output name=path::$(python -c "import sys; print(sys.executable)")

      - name: Install pipenv
        run: |
          python -m pip install pipenv

      - name: Install dependencies
        env:
          PIPENV_DEFAULT_PYTHON_VERSION: ${{ matrix.python-version }}
          PYTHONIOENCODING: "utf-8"
          GIT_ASK_YESNO: "false"
        run: |
          pipenv install --dev --python=${{ steps.python-path.outputs.path }}

      - name: Install extra dependency (pytest on python <= 3.7)
        if: ${{ matrix.python-version == '3.6' || matrix.python-version == '3.7' }}
        run: |
          pipenv install --dev importlib_metadata

      - name: Install extra dependency (pytest on windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          pipenv install --dev atomicwrites

      - name: Run tests
        env:
          PIPENV_DEFAULT_PYTHON_VERSION: ${{ matrix.python-version }}
          PIPENV_NOSPIN: "1"
          GIT_ASK_YESNO: "false"
          PYTHONIOENCODING: "utf-8"
        run: |
          pipenv run pytest -ra --full-trace --cov=persiantools tests/

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{matrix.os}}-${{ matrix.python-version }}
          parallel: true

  finish-test:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
